/* Switcharoo calculator. Math.js supplies dimensional arithmetic. */
function createSwitcharooCalculator(math) {
  const m=math.create(math.all,{number:'BigNumber',precision:64});
  m.config({number:'BigNumber',precision:64});
  const originalFactorial=m.factorial;
  m.import({factorial:x=>{if(Math.abs(Number(x))>500)throw Error('Value is too large');return originalFactorial(x)}},{override:true});
  const allowed=new Set('abs acos acosh acot acoth acsc acsch asec asech asin asinh atan atan2 atanh cbrt ceil cos cosh cot coth csc csch exp factorial fix floor gcd hypot lcm log log10 log2 max mean min mod nthRoot pow round sec sech sign sin sinh sqrt square tan tanh'.split(' '));
  const aliases={sf:'America/Los_Angeles','san francisco':'America/Los_Angeles',sfo:'America/Los_Angeles',la:'America/Los_Angeles','los angeles':'America/Los_Angeles',lax:'America/Los_Angeles',ldn:'Europe/London',london:'Europe/London',lhr:'Europe/London',nyc:'America/New_York',ny:'America/New_York','new york':'America/New_York',jfk:'America/New_York',utc:'UTC',gmt:'UTC',seoul:'Asia/Seoul',tokyo:'Asia/Tokyo',paris:'Europe/Paris',berlin:'Europe/Berlin',sydney:'Australia/Sydney',singapore:'Asia/Singapore',dubai:'Asia/Dubai','sao paulo':'America/Sao_Paulo',chicago:'America/Chicago',denver:'America/Denver',india:'Asia/Kolkata',beijing:'Asia/Shanghai',taipei:'Asia/Taipei','hong kong':'Asia/Hong_Kong'};
  const key=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/_/g,' ').toLowerCase().trim();
  for(const z of Intl.supportedValuesOf('timeZone')) if(!aliases[key(z.split('/').pop())])aliases[key(z.split('/').pop())]=z;
  const zone=s=>aliases[key(s)]||(()=>{try{new Intl.DateTimeFormat('en',{timeZone:s});return s}catch{return null}})();
  const result=(value,kind='Calculation',raw=value)=>({value:String(value),raw:String(raw),kind});
  const dateFmt=d=>d.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric'});
  const clock=(d,z)=>d.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:z});
  function parts(d,z){const a=new Intl.DateTimeFormat('en-US',{timeZone:z,year:'numeric',month:'numeric',day:'numeric',hour:'numeric',minute:'numeric',second:'numeric',hourCycle:'h23'}).formatToParts(d);return Object.fromEntries(a.filter(x=>x.type!=='literal').map(x=>[x.type,+x.value]));}
  function offset(d,z){const p=parts(d,z);return (Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second)-Math.floor(+d/1000)*1000)/60000;}
  function localTime(hour,minute,z,now){const p=parts(now,z),wall=Date.UTC(p.year,p.month-1,p.day,hour,minute);let d=new Date(wall);for(let i=0;i<4;i++)d=new Date(wall-offset(d,z)*60000);const check=parts(d,z);if(check.hour!==hour||check.minute!==minute)throw Error('That local time does not exist on this date');return d;}
  function span(seconds){const sign=seconds<0?'-':'';let s=Math.abs(Math.round(seconds));const a=[];for(const [n,label] of [[86400,'day'],[3600,'hr'],[60,'min'],[1,'sec']]){const v=Math.floor(s/n);s%=n;if(v)a.push(v+' '+label+(label==='day'&&v!==1?'s':''));}return sign+(a.join(' ')||'0 sec');}
  function parseDate(text,now){const t=text.trim().toLowerCase();let d=new Date(now);if(t==='today')return d;if(t==='tomorrow'){d.setDate(d.getDate()+1);return d}if(t==='yesterday'){d.setDate(d.getDate()-1);return d}const week=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];let match=t.match(/^(?:next )?(sunday|monday|tuesday|wednesday|thursday|friday|saturday)$/);if(match){let delta=(week.indexOf(match[1])-d.getDay()+7)%7;if(!delta||t.startsWith('next '))delta=delta||7;d.setDate(d.getDate()+delta);return d}if(/^\d{4}-\d{2}-\d{2}$/.test(t)){const [y,mo,day]=t.split('-').map(Number);d=new Date(y,mo-1,day);if(d.getFullYear()!==y||d.getMonth()!==mo-1||d.getDate()!==day)return null;return d}if(!/^(?:\d{1,2}\s+[a-z]{3,9}|[a-z]{3,9}\s+\d{1,2})(?:,?\s+\d{4})?$/i.test(t))return null;const explicit=/\b\d{4}\b/.test(t);d=new Date(explicit?t:t+' '+now.getFullYear());return Number.isNaN(+d)?null:d;}
  function dateAndTime(input,now){let a;
    if((a=input.match(/^time in (.+)$/i))){const delayed=a[1].match(/^(\d+(?:\.\d+)?)\s*(hours?|hrs?|minutes?|mins?|days?)(?: in (.+))?$/i);if(delayed){const amount=+delayed[1]*(/^d/i.test(delayed[2])?86400000:/^h/i.test(delayed[2])?3600000:60000),z=delayed[3]?zone(delayed[3]):Intl.DateTimeFormat().resolvedOptions().timeZone;if(!z)throw Error('Unknown time zone');const d=new Date(+now+amount);return result(clock(d,z),'Time · '+z,d.toISOString())}const z=zone(a[1]);if(z)return result(clock(now,z),'Time · '+z,now.toISOString());return null;}
    if((a=input.match(/^(?:time )?diff (.+)$/i))){const z=zone(a[1]);if(!z)return null;const local=Intl.DateTimeFormat().resolvedOptions().timeZone;const minutes=offset(now,z)-offset(now,local);return result(span(minutes*60),z+' '+(minutes>=0?'ahead':'behind'),String(minutes/60));}
    if((a=input.match(/^(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\s+(.+?)\s+(?:in|to)\s+(.+)$/i))){const from=zone(a[4]),to=zone(a[5]);if(from&&to){let h=+a[1],min=+(a[2]||0);if(a[3]){if(h<1||h>12)throw Error('Use a time from 1 to 12');h=h%12+(a[3].toLowerCase()==='pm'?12:0)}if(h>23||min>59)throw Error('Invalid time');const d=localTime(h,min,from,now);return result(clock(d,to),'Time · '+to,d.toISOString())}}
    if((a=input.match(/^(?:days? )?(until|since) (.+)$/i))){let d=parseDate(a[2],now);if(d){const localDay=x=>Date.UTC(x.getFullYear(),x.getMonth(),x.getDate());let n=Math.round((localDay(d)-localDay(now))/86400000);if(a[1].toLowerCase()==='since')n=-n;return result(n+' days','Date difference',n)}}
    if((a=input.match(/^(today|tomorrow|yesterday|(?:next )?(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday)|[a-z]{3,9}\s+\d{1,2}(?:,?\s+\d{4})?|\d{4}-\d{2}-\d{2})\s*(\+|-|in)\s*(\d+)\s*(days?|weeks?|months?|years?)?$/i))){const d=parseDate(a[1],now);if(d){const n=+a[3]*(a[2]==='-'?-1:1),unit=(a[4]||'days').toLowerCase();if(n>365000)throw Error('Date offset is too large');if(unit.startsWith('month'))d.setMonth(d.getMonth()+n);else if(unit.startsWith('year'))d.setFullYear(d.getFullYear()+n);else d.setDate(d.getDate()+n*(unit.startsWith('week')?7:1));return result(dateFmt(d),'Date',d.toISOString())}}
    if((a=input.match(/^(\d{1,2})(?::(\d{2}))?\s*(am|pm)\s*([+-])\s*(\d+(?:\.\d+)?)$/i))){let h=+a[1];if(h<1||h>12||+(a[2]||0)>59)throw Error('Invalid time');const d=new Date(now);d.setHours(h%12+(a[3].toLowerCase()==='pm'?12:0),+(a[2]||0),0,0);d.setTime(+d+ +a[5]*3600000*(a[4]==='-'?-1:1));return result(clock(d,Intl.DateTimeFormat().resolvedOptions().timeZone),'Time',d.toISOString())}
    if(/^\d{4}-\d\d-\d\dT/.test(input)){const d=new Date(input);if(!Number.isNaN(+d))return result(dateFmt(d)+' · '+clock(d,Intl.DateTimeFormat().resolvedOptions().timeZone),'Local time',d.toISOString())}
    if((a=input.match(/^work(hours|days) in (\d{4})$/i))){const year=+a[2];if(year<1900||year>2200)throw Error('Use a year between 1900 and 2200');let days=0;for(let d=new Date(year,0,1);d.getFullYear()===year;d.setDate(d.getDate()+1))if(d.getDay()>0&&d.getDay()<6)days++;return result((days*(a[1].toLowerCase()==='hours'?8:1))+' '+a[1].toLowerCase(),'Weekdays · 8-hour days')}
    return null;
  }
  function normalize(s){return s.replace(/[×]/g,'*').replace(/[÷]/g,'/').replace(/[−–]/g,'-').replace(/π/g,'pi').replace(/\b(?:what is|what's|calculate|convert)\s+/i,'').replace(/\?$/,'').replace(/\b(?:multiplied by|times)\b/gi,'*').replace(/\bdivided by\b/gi,'/').replace(/\bplus\b/gi,'+').replace(/\bminus\b/gi,'-').replace(/\b(?:to the power of|power)\b/gi,'^').replace(/\bsquared\b/gi,'^2').replace(/\bcubed\b/gi,'^3').replace(/\bper\b/gi,'/').replace(/\b([kKMGTPEZY]?i?)([bB])ps\b/g,(_,p,b)=>(p==='K'?'k':p)+b+'/s').replace(/\b([kKmMgGtT])?(bits?|bytes?)\s*\/\s*(?:second|sec)s?\b/gi,(_,p='',b)=>(p.toLowerCase()==='k'?'k':p.toUpperCase())+(b.toLowerCase().startsWith('byte')?'B':'b')+'/s').replace(/\bcelsius\b/gi,'degC').replace(/\bfahrenheit\b/gi,'degF').replace(/°\s*C\b/g,'degC').replace(/°\s*F\b/g,'degF').replace(/\bfeet\b/gi,'ft').replace(/\b(?:inches)\b/gi,'inch').replace(/\bkilometers\b/gi,'km').replace(/\bkilograms\b/gi,'kg').replace(/\bdegrees\b/gi,'deg').replace(/\bKB\b/g,'kB').replace(/\bkbps\b/g,'kb/s').replace(/(\d),(?=\d{3}(?:\D|$))/g,'$1').trim();}
  function arithmetic(s){const tree=m.parse(s);let count=0;tree.traverse(node=>{if(++count>100)throw Error('Expression is too long');if(!['ConstantNode','SymbolNode','OperatorNode','FunctionNode','ParenthesisNode'].includes(node.type))throw Error('Use a single expression');if(node.type==='FunctionNode'&&!allowed.has(node.fn.name))throw Error('Unknown function');if(node.type==='OperatorNode'&&['factorial','pow'].includes(node.fn)){const last=node.args[node.args.length-1];if(last.type==='ConstantNode'&&Math.abs(Number(last.value))>(node.fn==='factorial'?500:10000))throw Error('Value is too large')}});const value=tree.compile().evaluate();const raw=m.format(value,{precision:32}),formatted=m.format(value,{precision:14});if(raw.length>300||/^(?:NaN|Infinity|-Infinity)$/.test(raw))throw Error('Result is not finite');return result(formatted,value?.isUnit?'Unit conversion':'Calculation',raw)}
  return function evaluate(input,context={}){let s=input.trim();if(!s||s.length>400)return null;const now=context.now||new Date();let a;try{
    const dt=dateAndTime(s,now);if(dt)return dt;
    if((a=s.match(/^([\d.]+)\s*(?:inches?|in|cm|mm)\s+(?:in|to)\s+px\s+at\s+([\d.]+)\s*(?:ppi|dpi)$/i))){const inches=Number(m.evaluate(normalize(s.split(/\s+(?:in|to)\s+px/i)[0])+' to inch').toNumber('inch'));return result(inches*+a[2]+' px','Pixel conversion')}
    if((a=s.match(/^([\d.]+)\s*px\s+(?:in|to)\s+(inches?|cm|mm)\s+at\s+([\d.]+)\s*(?:ppi|dpi)$/i))){if(+a[3]<=0)throw Error('PPI must be positive');return arithmetic(`${+a[1]/+a[3]} inch to ${a[2].replace(/inches?/i,'inch')}`)}
    if((a=s.match(/^(.+?)\s+(?:to|in)\s+timespan$/i)))return result(span(Number(m.evaluate(normalize(a[1])+' to s').toNumber('s'))),'Duration');
    if((a=s.match(/^([\d.]+)\s*(?:h|hours?)\s+(?:in|to)\s+workdays$/i)))return result(+a[1]/8+' workdays','8-hour workday');
    if((a=s.match(/^([\d.]+)\s*workdays\s+(?:in|to)\s+(?:h|hours?)$/i)))return result(+a[1]*8+' hours','8-hour workday');
    if((a=s.match(/^(?:how long (?:to )?(?:download|transfer)\s+)?(.+?)\s+at\s+(.+?)(?:\s+(?:in|to)\s+(seconds?|minutes?|hours?|s|min|h))?$/i))&&/\b(?:[kKMGTPE]?i?B|bytes?|gigabytes?|megabytes?)\b/.test(a[1])){const calc=arithmetic(`(${normalize(a[1])}) / (${normalize(a[2])}) to ${a[3]||'s'}`);if(a[3])return calc;return result(span(Number(m.evaluate(`(${normalize(a[1])}) / (${normalize(a[2])}) to s`).toNumber('s'))),'Transfer time · theoretical',calc.raw)}
    let currency=null;if(/(?:\b(?:USD|EUR|GBP|JPY|CAD|AUD|CHF|CNY|KRW|INR|BTC|ETH)\b|[$€£¥]).*\b(?:to|in)\b/i.test(s))return {value:'Live rates required',raw:'',kind:'Currency conversion',unavailable:true};
    if(/[$€£]/.test(s)){currency=s.includes('$')?'USD':s.includes('€')?'EUR':'GBP';s=s.replace(/[$€£]/g,'')}
    s=normalize(s);
    if((a=s.match(/^([\d.]+)%\s+(?:of)\s+(.+)$/i)))s=`(${a[1]}/100)*(${a[2]})`;
    else if((a=s.match(/^([\d.]+)%\s+(off|tip on)\s+(.+)$/i)))s=a[2].toLowerCase()==='off'?`(${a[3]})*(1-${a[1]}/100)`:`(${a[3]})*${a[1]}/100`;
    else if((a=s.match(/^ratio of (.+) to (.+)$/i)))s=`(${a[1]})/(${a[2]})`;
    else if((a=s.match(/^(square|cube) root of (.+)$/i)))s=`${a[1].toLowerCase()==='square'?'sqrt':'cbrt'}(${a[2]})`;
    if(/^[\d.]+[kKM]$/.test(s))s=String(parseFloat(s)*(s.endsWith('M')?1e6:1e3));
    if(!/\d|[+*/^!%()]|\b(?:pi|e)\b/.test(s))return null;
    const answer=arithmetic(s);if(currency){answer.value+=' '+currency;answer.raw+=' '+currency}return answer;
  }catch(e){if(/(?:[+*/^!%()]|\b(?:to|in|root|squared|cubed)\b)/i.test(s))return {value:'Check expression or units',raw:'',kind:'Calculation',error:true};return null}};
}
if(typeof module!=='undefined')module.exports={createSwitcharooCalculator};
